# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default:
            hosts: ['%env(ELASTICSEARCH_URL)%']
    indexes:
        etablissement:
            persistence:
                driver: orm
                model: App\Entity\Admin\Etablissement
                elastica_to_model_transformer:
                    ignore_missing: true
                listener:
                    enabled: true
                    defer: false   # false = update direct, true = différé
                    insert: true   # indexe à la création
                    update: true   # met à jour à la modification
                    delete: true   # supprime à la suppression
                provider: ~
                finder: ~
            properties:
                name:
                    type: text
                zipcode:
                    type: text
                city:
                    type: text
                typeEtablissement:
                    type: object
                    properties :
                        id: ~
        article :
            persistence:
                driver: orm
                model: App\Entity\Webapp\Article
                elastica_to_model_transformer:
                    ignore_missing: true
                listener:
                    enabled: true
                    defer: false   # false = update direct, true = différé
                    insert: true   # indexe à la création
                    update: true   # met à jour à la modification
                    delete: true   # supprime à la suppression
                provider: ~
                finder: ~
            properties:
                title:
                    type: text
                content:
                    type: text
                theme:
                    type: object
                    properties:
                        id: ~
                support:
                    type: object
                    properties:
                        id: ~
                etablissement:
                    type: object
                    properties:
                        id: ~
                typeEtablissement:
                    property_path: etablissement?.typeEtablissement?.id
                updatedAt:
                    type: date
