services:

  php:
    build:
      context: .
      args:
        - SYMFONY_VERSION=${SYMFONY_VERSION:-8.0.*}
        - PHP_VERSION=${PHP_VERSION:-8.4}
        - GIT_USER_EMAIL=${GIT_USER_EMAIL:-youremail@email.com}
        - GIT_USER_NAME=${GIT_USER_NAME:-yourname}
    container_name: francascc2025_php
    restart: unless-stopped
    ports:
      - "84:80"
    #  - "443:443"
    #  - "443:443/udp"
    volumes:
      - ./:/app
    environment:
      - SERVER_NAME=:80
    depends_on:
      - db
    networks:
      - francascc2025

  ###> doctrine/doctrine-bundle ###
  db:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: francascc2025_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    networks:
      - francascc2025
  ###< doctrine/doctrine-bundle ###

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.16
    container_name: francascc2025_search
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ports:
      - "9201:9200"
      - "9301:9300"
    restart: always
    networks:
      - francascc2025

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
  ###< doctrine/doctrine-bundle ###
  esdata:

networks:
  francascc2025:
    external: true
